#!/usr/bin/env bash
#
# scripts/lib/heredoc-escape-lint-selftest.sh — selftest for
# scripts/lib/heredoc-escape-lint.sh (QA-CRIER-32).
#
# Proves the lint still behaves, on fixtures it builds under ${TMPDIR:-/tmp},
# without touching the live generator:
#
#   1. ACCEPT   the CURRENT live generator unchanged (exit 0), explicitly
#               naming what it scanned;
#   2. REJECT   a seeded bad fixture carrying a backticked command AND a
#               double-escaped `\$\(curl\)` AND a bare `$VAR`, with line
#               numbers on the findings;
#   3. REJECT   each broken class in isolation — unescaped backtick (the
#               09-21 comment shape), double-escaped `\$(`, bare
#               `$UNBOUND_VAR` (the set -u killer), and the never-legitimate
#               bare specials `$?` / `${…}`;
#   4. REJECT   (fail-closed) a generator path that does not exist — exit 2
#               naming the path, never a silent skip;
#   5. NEUTER   a copy of the lint with its reject choke-point neutered must
#               ACCEPT the same bad fixture the real lint rejects — so a
#               green selftest cannot be vacuous (cmp-guarded sed on
#               NEUTER-MARK[reject], the same pattern check-gofmt.sh uses).
#
# exit 0 all checks behaved · exit 1 any check failed

set -euo pipefail

PROG=$(basename "$0")
HERE=$(cd "$(dirname "$0")" && pwd)
LINT="$HERE/heredoc-escape-lint.sh"
DEFAULT_GENERATOR="$HOME/.hermes/scripts/bunker-qa.sh"

[ -r "$LINT" ] || { printf '%s: lint script missing: %s\n' "$PROG" "$LINT" >&2; exit 2; }

_TMP=""

_cleanup() {
  if [ -n "$_TMP" ]; then
    rm -rf "$_TMP"
    _TMP=""
  fi
  return 0
}

main() {
  local fails=0 checks=0
  _TMP=$(mktemp -d "${TMPDIR:-/tmp}/heredoc-escape-lint-selftest.XXXXXX") || {
    printf '%s: mktemp -d failed\n' "$PROG" >&2
    return 1
  }
  local tmp=$_TMP
  trap '_cleanup' EXIT

  # seed FILE BODY_FILE — a generator-shaped fixture: a build_remote_script()
  # function whose unquoted heredoc body is the PLACEHOLDER marker line
  # replaced by the single line in BODY_FILE (read with getline so backslashes
  # survive verbatim — awk -v would eat them as escape sequences).
  seed() { # FILE BODY_FILE
    cat >"$1" <<'GEN'
#!/usr/bin/env bash
set -euo pipefail
# generated by bunker-qa.sh (fixture copy)
build_remote_script() { # args: proj install_cmd ci_cmd native_cmd
  local proj="$1" install_cmd="$2" ci_cmd="$3" native_cmd="$4"
  cat <<EOF
#!/usr/bin/env bash
PROJ='\$proj'
EVID=~/qa-evidence.jsonl
LOGD=~/qa-logs-\$\$
BODY_LINE_PLACEHOLDER
EOF
}
GEN
    awk -v bf="$2" '
      BEGIN { body = ""; while ((getline l < bf) > 0) body = l }
      { if ($0 == "BODY_LINE_PLACEHOLDER") print body; else print }
    ' "$1" >"$1.new" && mv "$1.new" "$1"
  }

  # body BODYLINE — write a single body line to a scratch file, print its path
  local bodyfile=""
  body() { # BODYLINE → prints path of a file holding the line verbatim
    bodyfile="$tmp/body.$$"
    printf '%s\n' "$1" >"$bodyfile"
    printf '%s' "$bodyfile"
  }

  local out="" rc=0 bf=""

  # run_lint SCRIPT [ARG…] — capture stdout+stderr and the exit code without
  # tripping `set -e`: an assignment whose command substitution fails IS a
  # failing command, so the bare `out="$(…)"` + `rc=$?` shape died at the
  # first expected-rejection check before printing anything.
  run_lint() {
    rc=0
    out="$(bash "$@" 2>&1)" || rc=$?
  }

  # ── 1a. the CURRENT live generator is scanned, and the scan NAMES it ────────
  # The generator is fleet-shared and edited by live workers; it can carry real
  # violations at selftest time — it does today: 3 unescaped backticks at lines
  # 857/982/984 (QA-CRIER-19's ui-probe arm, 2026-09-21; PATH-shim evidence in
  # the QA-CRIER-32 evidence artifact shows `curl -sSL`, `pkill -f 'npm run
  # dev'` and `pkill -f 'node .*vite'` EXECUTE on this host at every
  # generation run). This check therefore asserts the scan comes back
  # well-formed — a heredoc region found, a verdict line issued — and names
  # the generator; the accept-path itself is proven in 1b on a scrubbed copy.
  checks=$((checks + 1))
  if [ ! -r "$DEFAULT_GENERATOR" ]; then
    printf '%s selftest: FAIL: live generator %s is not readable — cannot run the scan check\n' "$PROG" "$DEFAULT_GENERATOR" >&2
    fails=$((fails + 1))
  else
    run_lint "$LINT"
    if ! printf '%s' "$out" | grep -q "of $DEFAULT_GENERATOR"; then
      printf '%s selftest: FAIL: the live-generator scan did not report a heredoc region naming %s\n  output: %s\n' "$PROG" "$DEFAULT_GENERATOR" "$out" >&2
      fails=$((fails + 1))
    elif ! printf '%s' "$out" | grep -Eq '(PASS|FAIL) — [0-9]+ violation'; then
      printf '%s selftest: FAIL: the live-generator scan produced no verdict line\n  output: %s\n' "$PROG" "$out" >&2
      fails=$((fails + 1))
    else
      printf 'PASS: the live generator is scanned end-to-end, region and verdict reported (%s)\n' \
        "$(printf '%s' "$out" | grep -m1 -E '(PASS|FAIL) — [0-9]+ violation' | sed 's/^.*FAIL  /findings incl. /;s/ — .*//')"
    fi
  fi

  # ── 1b. the lint's ACCEPT path: a clean FULL-SCALE generator copy passes ────
  # Copy the live generator and strip ONLY its unescaped backticks (the
  # documented convention is zero unescaped backticks; the escaped `\`b
  # forms stay). The real lint must then accept the copy (rc=0, PASS,
  # naming the copy) — proving the accept path works on a real-scale file,
  # not just on tiny fixtures, without editing the live file (read-only).
  checks=$((checks + 1))
  sed -e 's/\([^\]\)`/\1/g' -e 's/^`//' "$DEFAULT_GENERATOR" >"$tmp/live-scrubbed.sh" || {
    printf '%s selftest: FAIL: could not build the scrubbed generator copy\n' "$PROG" >&2
    fails=$((fails + 1))
  }
  run_lint "$LINT" "$tmp/live-scrubbed.sh"
  if [ "$rc" -ne 0 ]; then
    printf '%s selftest: FAIL: the backtick-scrubbed generator copy was REJECTED (rc=%d) — the accept path is broken\n  output:\n%s\n' "$PROG" "$rc" "$out" >&2
    fails=$((fails + 1))
  elif ! printf '%s' "$out" | grep -q 'PASS — 0 violation'; then
    printf '%s selftest: FAIL: scrubbed copy accepted without a PASS verdict\n  output: %s\n' "$PROG" "$out" >&2
    fails=$((fails + 1))
  elif ! printf '%s' "$out" | grep -q "$tmp/live-scrubbed.sh"; then
    printf '%s selftest: FAIL: the PASS verdict did not name the scrubbed copy\n  output: %s\n' "$PROG" "$out" >&2
    fails=$((fails + 1))
  else
    printf 'PASS: a backtick-scrubbed full-scale generator copy is ACCEPTED (rc=0), scan named:\n  %s\n' \
      "$(printf '%s' "$out" | grep -m1 'PASS — 0 violation')"
  fi

  # ── 2. seeded double-class bad fixture is REJECTED with line numbers ────────
  checks=$((checks + 1))
  bf=$(body 'BX_TAG=`hostname` && T=\\$(curl -fsSL https://x | head -1) && echo $T')
  seed "$tmp/bad-double.sh" "$bf"
  run_lint "$LINT" "$tmp/bad-double.sh"
  if [ "$rc" -eq 0 ]; then
    printf '%s selftest: FAIL: the seeded bad fixture (backticked command + double-escaped \\$(curl) + bare $T) was ACCEPTED (rc=0)\n  output: %s\n' "$PROG" "$out" >&2
    fails=$((fails + 1))
  elif ! printf '%s' "$out" | grep -q 'FAIL  backtick'; then
    printf '%s selftest: FAIL: bad fixture rejected but no backtick finding (rc=%d)\n  output: %s\n' "$PROG" "$rc" "$out" >&2
    fails=$((fails + 1))
  elif ! printf '%s' "$out" | grep -q 'double-escape-\$'; then
    printf '%s selftest: FAIL: bad fixture rejected but no double-escape finding (rc=%d)\n  output: %s\n' "$PROG" "$rc" "$out" >&2
    fails=$((fails + 1))
  elif ! printf '%s' "$out" | grep -Eq 'line [0-9]+'; then
    printf '%s selftest: FAIL: rejections carried no line numbers\n  output: %s\n' "$PROG" "$out" >&2
    fails=$((fails + 1))
  else
    printf 'PASS: the seeded double-class fixture (backticked command + double-escaped \\$(curl) + bare $T) is rejected with line numbers (rc=%d)\n' "$rc"
  fi

  # ── 3a. unescaped backtick alone is REJECTED (the 09-21 comment shape) ──────
  checks=$((checks + 1))
  bf=$(body '# a bare `curl -sSL` mention in a comment')
  seed "$tmp/backtick.sh" "$bf"
  run_lint "$LINT" "$tmp/backtick.sh"
  if [ "$rc" -eq 0 ]; then
    printf '%s selftest: FAIL: an unescaped backtick in a COMMENT line was ACCEPTED (rc=0) — the exact 09-21 incident shape\n  output: %s\n' "$PROG" "$out" >&2
    fails=$((fails + 1))
  elif ! printf '%s' "$out" | grep -q 'FAIL  backtick'; then
    printf '%s selftest: FAIL: backtick fixture rejected without a backtick finding\n  output: %s\n' "$PROG" "$out" >&2
    fails=$((fails + 1))
  else
    printf 'PASS: an unescaped backtick in a comment line is rejected (rc=%d) — the 09-21 incident shape\n' "$rc"
  fi

  # ── 3b. double-escaped \\$( alone is REJECTED ───────────────────────────────
  checks=$((checks + 1))
  bf=$(body 'probe=\\$(curl -fsSL https://x | head -1)')
  seed "$tmp/double.sh" "$bf"
  run_lint "$LINT" "$tmp/double.sh"
  if [ "$rc" -eq 0 ]; then
    printf '%s selftest: FAIL: a double-escaped \\$( fixture was ACCEPTED (rc=0)\n  output: %s\n' "$PROG" "$out" >&2
    fails=$((fails + 1))
  elif ! printf '%s' "$out" | grep -q 'double-escape-\$'; then
    printf '%s selftest: FAIL: double-escape fixture rejected without a double-escape finding\n  output: %s\n' "$PROG" "$out" >&2
    fails=$((fails + 1))
  else
    printf 'PASS: a double-escaped \\$( (the incident-1 shape) is rejected (rc=%d)\n' "$rc"
  fi

  # ── 3c. bare $UNBOUND_VAR under set -u is REJECTED ──────────────────────────
  checks=$((checks + 1))
  bf=$(body 'say $UNBOUND_VAR')
  seed "$tmp/bare.sh" "$bf"
  run_lint "$LINT" "$tmp/bare.sh"
  if [ "$rc" -eq 0 ]; then
    printf '%s selftest: FAIL: bare $UNBOUND_VAR was ACCEPTED (rc=0) — set -u would abort generation for ALL cells\n  output: %s\n' "$PROG" "$out" >&2
    fails=$((fails + 1))
  elif ! printf '%s' "$out" | grep -q 'bare-\$-token'; then
    printf '%s selftest: FAIL: bare-variable fixture rejected without a bare-\\$-token finding\n  output: %s\n' "$PROG" "$out" >&2
    fails=$((fails + 1))
  else
    printf 'PASS: a bare $UNBOUND_VAR (the set -u killer) is rejected (rc=%d)\n' "$rc"
  fi

  # ── 3d. bare $? and ${…} — never legitimate in the body ─────────────────────
  checks=$((checks + 1))
  bf=$(body 'rc=\$(curl -s http://x); echo \$rc $? ${WHATEVER}')
  seed "$tmp/special.sh" "$bf"
  run_lint "$LINT" "$tmp/special.sh"
  if [ "$rc" -eq 0 ]; then
    printf '%s selftest: FAIL: bare $? / ${…} were ACCEPTED (rc=0)\n  output: %s\n' "$PROG" "$out" >&2
    fails=$((fails + 1))
  elif ! printf '%s' "$out" | grep -q 'bare-\$-special'; then
    printf '%s selftest: FAIL: specials fixture rejected without a bare-\\$-special finding\n  output: %s\n' "$PROG" "$out" >&2
    fails=$((fails + 1))
  else
    printf 'PASS: bare $? and ${…} are rejected (rc=%d)\n' "$rc"
  fi

  # ── 4. missing file is exit 2 naming the path (fail closed) ─────────────────
  checks=$((checks + 1))
  run_lint "$LINT" "$tmp/no-such-generator.sh"
  if [ "$rc" -ne 2 ]; then
    printf '%s selftest: FAIL: a missing generator path returned rc=%d, expected 2\n  output: %s\n' "$PROG" "$rc" "$out" >&2
    fails=$((fails + 1))
  elif ! printf '%s' "$out" | grep -q "$tmp/no-such-generator.sh"; then
    printf '%s selftest: FAIL: the missing-path exit 2 did not name the path\n  output: %s\n' "$PROG" "$out" >&2
    fails=$((fails + 1))
  else
    printf 'PASS: a missing generator path is exit 2 naming the path (rc=%d)\n' "$rc"
  fi

  # ── 5. NEUTER PROOF — neutered reject-path ACCEPTS the bad fixture ──────────
  # Every rejection funnels through _reject (NEUTER-MARK[reject]). A copy
  # whose VIOL_COUNT increment is neutered counts nothing, so its verdict
  # collapses to PASS: if it still ACCEPTS what the real lint REJECTS, the
  # rejection provably comes from the verdict path — not from an empty
  # region, a wrong file, or bash exiting nonzero by accident.
  checks=$((checks + 1))
  local neutered="$tmp/neutered-lint.sh"
  cp "$LINT" "$neutered"
  sed -i.tmp -e 's|^  VIOL_COUNT=\$((VIOL_COUNT + 1))$|  : neutered|' "$neutered"
  rm -f "$neutered.tmp"
  if cmp -s "$LINT" "$neutered"; then
    printf '%s selftest: FAIL: the neuter sed no longer matches the reject choke-point (NEUTER-MARK[reject]) — the causality proof would be vacuous\n' "$PROG" >&2
    fails=$((fails + 1))
  else
    run_lint "$neutered" "$tmp/bad-double.sh"
    if [ "$rc" -ne 0 ]; then
      printf '%s selftest: FAIL: NEUTER PROOF: with the reject-path neutered the bad fixture is STILL rejected (rc=%d) — the rejection does not come from the verdict path\n  output: %s\n' "$PROG" "$rc" "$out" >&2
      fails=$((fails + 1))
    else
      printf 'PASS: NEUTER PROOF: the neutered copy differs (cmp) and ACCEPTS the same fixture the real lint rejects (rc=0) — the rejection is caused by the verdict path\n'
    fi
  fi

  if [ "$fails" -ne 0 ]; then
    printf '%s selftest: %d/%d checks behaved — FAIL\n' "$PROG" "$((checks - fails))" "$checks" >&2
    return 1
  fi
  printf '%s selftest: %d/%d checks behaved\n' "$PROG" "$checks" "$checks"
  return 0
}

main "$@"
exit $?
